import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sample Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-4 md:px-0 md:w-1/2 md:mx-auto my-5">
          <nav className="flex text-center justify-between py-2 border-b-2 border-black">
            <Link href={'/'} className=" text-3xl font-bold uppercase">Sample_Share</Link>
            <Link href={'/posts/create'} className="bg-black text-white px-2 py-1 rounded-lg">+</Link>
          </nav>
          {children}
          <footer className="fixed bottom-0 items-center justify-center w-full">
            <p className="text-center my-3 font-semibold text-xs">Copyright by @yuyalwinoo</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
